# Generated by Django 4.1.6 on 2023-02-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户账号')),
                ('user_password', models.CharField(max_length=32, verbose_name='用户密码')),
            ],
        ),
    ]
